### ISSUE TITLE
Sorting Lerna / Package Deps

### ISSUE THREAD

**Issue by calumpeak** [redux-offline/tools#1]
Just going through the monorepo - I'm fairly familiar with Lerna as I use it for a large project currently. 
There's some changes I'm going to raise to sort things out based on a PR that didn't make it in last time:

- Eslint can be done from root for all packages and run in CI (we could also implement `lint-staged` as a pre-commit hook via `husky` or something similar)
- Prettier can also be treated the same way as ☝️ 
- Each package should have it's own build dependencies specified so they can be built in isolation (babelrc, flow etc), these files IMO shouldn't be in root.

I would also like to standardise commit messages, how do we feel about an implementation of [commitizen](https://github.com/commitizen/cz-cli) to ensure we have a good/descriptive commit history from all contributors? This is something I think should also be considered for offline core as well.

Thoughts?

**Comment by sorodrigo** [comment]
I agree that Eslint and Prettier should be in the root, but I think Babel, Flow should be there too. Check out the React monorepo they have their build dependencies at [top level](https://github.com/facebook/react/blob/master/package.json) and their [per package dependencies](https://github.com/facebook/react/blob/master/packages/react/package.json). Also the [docs](https://github.com/lerna/lerna#common-devdependencies) advises to do this.

I might be wrong, but I think we could use a global config and just override it locally if needed no?

About the commitizen suggestion I have tried it before in other projects, and found it to be more friction than help. I would prefer not including this, it could act as a wall against contributors.

**Comment by calumpeak** [comment]
Yeah that sounds about right - I'll sort out the deps that way :) 

And no worries on `cz`, was just a suggestion 👍
